name: Terraform Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/README.md'
      - '.github/workflows/terraform-checks.yml'

jobs:
  get-directories:
    name: Get Terraform Directories
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.set-dirs.outputs.dirs }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Find Terraform Directories
        id: set-dirs
        run: |
          DIRS=$(find . -type f -name "*.tf" -exec dirname {} \; | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "dirs=$DIRS" >> $GITHUB_OUTPUT

  terraform-checks:
    name: Terraform Checks
    needs: get-directories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.get-directories.outputs.dirs) }}
    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for README
        run: |
          if [ ! -f "README.md" ]; then
            echo "Error: README.md is missing in directory ${{ matrix.directory }}"
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"

      - name: Terraform Format Check
        id: fmt
        run: |
          terraform fmt -check
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: |
          terraform init -backend=false

      - name: Terraform Validate
        id: validate
        run: |
          terraform validate
