name: Terraform Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/README.md'
      - '.github/workflows/terraform-checks.yml'

jobs:
  get-directories:
    name: Get Changed Terraform Directories
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.set-dirs.outputs.dirs }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Find Changed Terraform Directories
        id: set-dirs
        run: |
          git fetch origin main
          # Get list of changed files in the PR
          CHANGED_FILES=$(git diff --name-only origin/main HEAD | grep '\.tf$' || true)
          if [ -n "$CHANGED_FILES" ]; then
            # Extract unique directories from changed .tf files
            DIRS=$(echo "$CHANGED_FILES" | xargs -I {} dirname {} | sort -u | jq -R -s -c 'split("\n")[:-1]')
            echo "dirs=$DIRS" >> $GITHUB_OUTPUT
          else
            # If no .tf files changed, return empty array to skip matrix
            echo "dirs=[]" >> $GITHUB_OUTPUT
          fi

  terraform-checks:
    name: Terraform Checks
    needs: get-directories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.get-directories.outputs.dirs) }}
    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for README
        run: |
          if [ ! -f "README.md" ]; then
            echo "Error: README.md is missing in directory ${{ matrix.directory }}"
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"

      - name: Terraform Format Check
        id: fmt
        run: |
          terraform fmt -check
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: |
          terraform init -backend=false

      - name: Terraform Validate
        id: validate
        run: |
          terraform validate

      - name: Terraform Plan
        if: endsWith(matrix.directory, '/solution')
        id: plan
        run: |
          terraform plan -no-color -input=false
